Bai_Project2!!/Models/Exam.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bai_Project2__.Models
{
    public class Exam
    {

        [Key]
        public int SubjectId { get; set; }
        [Required]
        public int StudentId { get; set; }
        [Range(0,100)]
        public int Mark { get; set; }

        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
   } 
}

Bai_Project2!!/Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bai_Project2__.Models;

namespace Bai_Project2__.Controllers
{
    public class ExamsController : Controller
    {
        private Model_Student_Contex db = new Model_Student_Contex();

        // GET: Exams
        public ActionResult Index(string search,string M, string mark)
        {
            var exams = from a in db.Exams
                        join b in db.Students
                        on a.StudentId equals b.StudentId
                        join c in db.Subjects
                        on a.SubjectId equals c.SubjectId
                        select a;

            if (!String.IsNullOrEmpty(search))
                exams = exams.Where(a => a.Student.StudentName.Contains(search));

            var SubjectList = new List<String>();
            var SubejectSQL = from d in db.Subjects
                              orderby d.SubjectId
                              select d.SubjectName;
            SubjectList.AddRange(SubejectSQL.Distinct());
            ViewBag.M = new SelectList(SubejectSQL);

            if (!String.IsNullOrEmpty(search))
                exams = exams.Where(b => b.Subject.SubjectName.Contains(M));

            var markList = new List<String>() {
                "Do","Truot"
            };
            ViewBag.mark = new SelectList(markList);
            if(!String.IsNullOrEmpty(mark) && mark.Equals("Do"))
            {
                exams = exams.Where(e => e.Mark >= 40);

            }
            else if (!String.IsNullOrEmpty(mark) && mark.Equals("Truot"))
            {
                exams = exams.Where(e => e.Mark <= 40);
            }
            /*ar exams = db.Exams.Include(e => e.Student);*/
            return View(exams.ToList());
        }

        // GET: Exams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            return View(exam);
        }

        // GET: Exams/Create
        public ActionResult Create()
        {
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "StudentName");
            return View();
        }

        // POST: Exams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubjectId,StudentId,Mark")] Exam exam)
        {
            if (ModelState.IsValid)
            {
                db.Exams.Add(exam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "StudentName", exam.StudentId);
            return View(exam);
        }

        // GET: Exams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "StudentName", exam.StudentId);
            return View(exam);
        }

        // POST: Exams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SubjectId,StudentId,Mark")] Exam exam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "StudentName", exam.StudentId);
            return View(exam);
        }

        // GET: Exams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            return View(exam);
        }

        // POST: Exams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Exam exam = db.Exams.Find(id);
            db.Exams.Remove(exam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bai_Project2!!/Views/Exams/Create.cshtml
@model Bai_Project2__.Models.Exam

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exam</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Bai_Project2!!/Views/Exams/Delete.cshtml
@model Bai_Project2__.Models.Exam

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exam</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Student.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mark)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Bai_Project2!!/Views/Exams/Details.cshtml
@model Bai_Project2__.Models.Exam

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Exam</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Student.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mark)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SubjectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bai_Project2!!/Views/Exams/Edit.cshtml
@model Bai_Project2__.Models.Exam

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exam</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SubjectId)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Bai_Project2!!/Views/Exams/Index.cshtml
@model IEnumerable<Bai_Project2__.Models.Exam>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm("Index", "Exams"))
    {
        <p>
            search: @Html.TextBox("Search");
            SubjectName:@Html.DropDownList("M","All")
            Mark: @Html.DropDownList("Do","Truot")
        </p>
        
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Student.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mark)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Student.StudentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mark)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SubjectId }) |
            @Html.ActionLink("Details", "Details", new { id=item.SubjectId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SubjectId })
        </td>
    </tr>
}

</table>